application: startupbidder
version: 201207111723
runtime: java

static_files:
  - include: /**.css
  - include: /**.js
  - include: /**.png
  - include: /**.jpg
  - include: /**.gif
  - include: /**.ico
  - include: /**.txt
  - include: /crossdomain.xml
  - include: /*

handlers:
  - url: /hello/*
    servlet: com.startupbidder.web.servlets.HelloServlet
  - url: /setup/*
    servlet: com.startupbidder.web.servlets.SetupServlet
  - url: /*
    servlet: com.startupbidder.web.FrontController
  - url: /remote_api
    servlet: com.google.apphosting.utils.remoteapi.RemoteApiServlet

welcome_files:
  - discover-page.html

inbound_services:
- warmup
