application: startupbidder
version: 1
runtime: java

static_files:
  - include: /**.css
  - include: /**.js
  - include: /**.png
  - include: /**.ico
  - include: /**.txt
  - include: /crossdomain.xml
  - include: /*

handlers:
  - url: /hello/*
    servlet: com.startupbidder.web.servlets.HelloServlet
  - url: /setup/*
    servlet: com.startupbidder.web.servlets.SetupServlet
  - url: /*
    servlet: com.startupbidder.web.FrontController
