application: startupbidder
version: 1
runtime: java

handlers:
  - url: /hello/*
    servlet: com.startupbidder.web.servlets.HelloServlet
  - url: /setup/*
    servlet: com.startupbidder.web.servlets.SetupServlet
  - url: /*
    servlet: com.startupbidder.web.FrontController
