application: startupbidder
version: 201207301517
runtime: java

static_files:
  - include: /**.css
  - include: /**.js
  - include: /**.png
  - include: /**.jpg
  - include: /**.gif
  - include: /**.ico
  - include: /**.txt
  - include: /crossdomain.xml
  - include: /*

handlers:
  - url: /hello/*
    servlet: com.startupbidder.web.servlets.HelloServlet
  - url: /setup/*
    servlet: com.startupbidder.web.servlets.SetupServlet
  - url: /twitter_login
    servlet: com.startupbidder.web.servlets.TwitterLoginServlet
  - url: /twitter_logout
    servlet: com.startupbidder.web.servlets.TwitterLogoutServlet
  - url: /twitter_callback
    servlet: com.startupbidder.web.servlets.TwitterCallbackServlet
  - url: /facebook_login
    servlet: com.startupbidder.web.servlets.FacebookLoginServlet
  - url: /facebook_logout
    servlet: com.startupbidder.web.servlets.FacebookLogoutServlet
  - url: /facebook_callback
    servlet: com.startupbidder.web.servlets.FacebookCallbackServlet
  - url: /*
    servlet: com.startupbidder.web.FrontController
  - url: /remote_api
    servlet: com.google.apphosting.utils.remoteapi.RemoteApiServlet

listeners:
   - com.startupbidder.web.servlets.WarmupListener

welcome_files:
  - discover-page.html

inbound_services:
  - warmup

admin_console:
  pages:
  - name: StartupBidder Test Page
    url: /hello
  - name: StartupBidder Setup Page
    url: /setup

sessions_enabled: true

threadsafe: true

  